//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsDetail
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int detail_id { get; set; }
        public int count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
